language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
    - pip install -r requirements.txt

script:
    - python setup.py test
    - coveralls
    - python setup.py bdist_wheel
    - python setup.py sdist

matrix:
  allow_failures:
    # currently no setuptools_scm for this, not our problem
    - python: "3.7-dev"
